// <auto-generated />
using System;
using Autoprint.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoprint.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoprint.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Emplacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CidrIpv4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Emplacements");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Imprimante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("int");

                    b.Property<bool>("EstParDefaut")
                        .HasColumnType("bit");

                    b.Property<bool>("EstPartagee")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Localisation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModeleId")
                        .HasColumnType("int");

                    b.Property<string>("NomAffiche")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomPartage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PiloteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmplacementId");

                    b.HasIndex("ModeleId");

                    b.HasIndex("PiloteId");

                    b.ToTable("Imprimantes");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Marques");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Modele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("MarqueId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MarqueId");

                    b.ToTable("Modeles");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Pilote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomFichierInf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pilotes");
                });

            modelBuilder.Entity("Autoprint.Server.Models.ServerSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("ServerSettings");

                    b.HasData(
                        new
                        {
                            Key = "SmtpHost",
                            Description = "Adresse SMTP",
                            Type = "STRING",
                            Value = "localhost"
                        },
                        new
                        {
                            Key = "SmtpPort",
                            Description = "Port SMTP",
                            Type = "INT",
                            Value = "25"
                        },
                        new
                        {
                            Key = "SmtpEnableSsl",
                            Description = "SSL/TLS",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "SmtpIgnoreCertError",
                            Description = "Ignorer Certificat",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "SmtpAuthRequired",
                            Description = "Auth requise ?",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "SmtpUser",
                            Description = "User SMTP",
                            Type = "STRING",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpPass",
                            Description = "Password SMTP",
                            Type = "PASSWORD",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpFromAddress",
                            Description = "Email Expéditeur",
                            Type = "STRING",
                            Value = "noreply@autoprint.local"
                        },
                        new
                        {
                            Key = "SmtpDisplayName",
                            Description = "Nom Affiché",
                            Type = "STRING",
                            Value = "Autoprint Server"
                        },
                        new
                        {
                            Key = "DriverPath",
                            Description = "Dossier Pilotes",
                            Type = "STRING",
                            Value = "drivers"
                        });
                });

            modelBuilder.Entity("Autoprint.Server.Models.Imprimante", b =>
                {
                    b.HasOne("Autoprint.Server.Models.Emplacement", "Emplacement")
                        .WithMany()
                        .HasForeignKey("EmplacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoprint.Server.Models.Modele", "Modele")
                        .WithMany()
                        .HasForeignKey("ModeleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoprint.Server.Models.Pilote", "Pilote")
                        .WithMany()
                        .HasForeignKey("PiloteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emplacement");

                    b.Navigation("Modele");

                    b.Navigation("Pilote");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Modele", b =>
                {
                    b.HasOne("Autoprint.Server.Models.Marque", "Marque")
                        .WithMany()
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marque");
                });
#pragma warning restore 612, 618
        }
    }
}
