// <auto-generated />
using System;
using Autoprint.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoprint.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoprint.Server.Models.Security.AdRoleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MappingType")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdIdentifier");

                    b.HasIndex("RoleId");

                    b.HasIndex("AdIdentifier", "RoleId")
                        .IsUnique();

                    b.ToTable("AdRoleMappings");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN_ACCESS",
                            Description = "Accès complet (SuperAdmin)"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PRINTER_READ",
                            Description = "Voir les imprimantes"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PRINTER_WRITE",
                            Description = "Ajouter/Modifier des imprimantes"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PRINTER_DELETE",
                            Description = "Supprimer des imprimantes"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PRINTER_SYNC",
                            Description = "Synchroniser vers Windows (Spouleur)"
                        },
                        new
                        {
                            Id = 6,
                            Code = "LOCATION_READ",
                            Description = "Voir les lieux"
                        },
                        new
                        {
                            Id = 7,
                            Code = "LOCATION_WRITE",
                            Description = "Ajouter/Modifier des lieux"
                        },
                        new
                        {
                            Id = 8,
                            Code = "LOCATION_DELETE",
                            Description = "Supprimer des lieux"
                        },
                        new
                        {
                            Id = 9,
                            Code = "DRIVER_READ",
                            Description = "Voir les pilotes"
                        },
                        new
                        {
                            Id = 10,
                            Code = "DRIVER_SCAN",
                            Description = "Scanner/Mettre à jour les pilotes"
                        },
                        new
                        {
                            Id = 11,
                            Code = "USER_READ",
                            Description = "Voir les utilisateurs"
                        },
                        new
                        {
                            Id = 12,
                            Code = "USER_WRITE",
                            Description = "Créer/Modifier utilisateurs"
                        },
                        new
                        {
                            Id = 13,
                            Code = "USER_DELETE",
                            Description = "Supprimer utilisateurs"
                        },
                        new
                        {
                            Id = 14,
                            Code = "SETTINGS_MANAGE",
                            Description = "Gérer la configuration serveur"
                        },
                        new
                        {
                            Id = 15,
                            Code = "ROLE_READ",
                            Description = "Voir les rôles et permissions"
                        },
                        new
                        {
                            Id = 16,
                            Code = "ROLE_WRITE",
                            Description = "Créer/Modifier des rôles"
                        },
                        new
                        {
                            Id = 17,
                            Code = "ROLE_DELETE",
                            Description = "Supprimer des rôles"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BRAND_READ",
                            Description = "Voir les marques"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BRAND_WRITE",
                            Description = "Ajouter/Modifier des marques"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BRAND_DELETE",
                            Description = "Supprimer des marques"
                        },
                        new
                        {
                            Id = 21,
                            Code = "MODEL_READ",
                            Description = "Voir les modèles"
                        },
                        new
                        {
                            Id = 22,
                            Code = "MODEL_WRITE",
                            Description = "Ajouter/Modifier des modèles"
                        },
                        new
                        {
                            Id = 23,
                            Code = "MODEL_DELETE",
                            Description = "Supprimer des modèles"
                        },
                        new
                        {
                            Id = 24,
                            Code = "AUDIT_READ",
                            Description = "Voir les logs d'audit"
                        });
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrateur Global",
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24
                        });
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForceChangePassword")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdUser")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Administrateur Local",
                            ForceChangePassword = false,
                            IsActive = true,
                            IsAdUser = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastPasswordChangeDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Autoprint.Shared.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Autoprint.Shared.Emplacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CidrIpv4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Emplacements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CidrIpv4 = "0.0.0.0/0",
                            Code = "ND",
                            DateModification = new DateTime(2025, 11, 26, 17, 54, 33, 881, DateTimeKind.Utc).AddTicks(6545),
                            EstSupprime = false,
                            Nom = "NON DÉFINI"
                        });
                });

            modelBuilder.Entity("Autoprint.Shared.Imprimante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CheminPartage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("int");

                    b.Property<bool>("EstPartagee")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Localisation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModeleId")
                        .HasColumnType("int");

                    b.Property<string>("NomAffiche")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomPartage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmplacementId");

                    b.HasIndex("ModeleId");

                    b.ToTable("Imprimantes");
                });

            modelBuilder.Entity("Autoprint.Shared.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Marques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateModification = new DateTime(2025, 11, 26, 17, 54, 33, 881, DateTimeKind.Utc).AddTicks(5924),
                            EstSupprime = false,
                            Nom = "NON DÉFINI"
                        });
                });

            modelBuilder.Entity("Autoprint.Shared.Modele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("MarqueId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PiloteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarqueId");

                    b.HasIndex("PiloteId");

                    b.ToTable("Modeles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateModification = new DateTime(2025, 11, 26, 17, 54, 33, 881, DateTimeKind.Utc).AddTicks(7165),
                            EstSupprime = false,
                            MarqueId = 1,
                            Nom = "GÉNÉRIQUE"
                        });
                });

            modelBuilder.Entity("Autoprint.Shared.Pilote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstInstalle")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pilotes");
                });

            modelBuilder.Entity("Autoprint.Shared.ServerSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("ServerSettings");

                    b.HasData(
                        new
                        {
                            Key = "SmtpHost",
                            Description = "Adresse SMTP",
                            Type = "STRING",
                            Value = "localhost"
                        },
                        new
                        {
                            Key = "SmtpPort",
                            Description = "Port SMTP",
                            Type = "INT",
                            Value = "25"
                        },
                        new
                        {
                            Key = "SmtpEnableSsl",
                            Description = "SSL/TLS",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "SmtpIgnoreCertError",
                            Description = "Ignorer Certificat",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "SmtpAuthRequired",
                            Description = "Auth requise ?",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "SmtpUser",
                            Description = "User SMTP",
                            Type = "STRING",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpPass",
                            Description = "Password SMTP",
                            Type = "PASSWORD",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpFromAddress",
                            Description = "Email Expéditeur",
                            Type = "STRING",
                            Value = "noreply@autoprint.local"
                        },
                        new
                        {
                            Key = "SmtpDisplayName",
                            Description = "Nom Affiché",
                            Type = "STRING",
                            Value = "Autoprint Server"
                        },
                        new
                        {
                            Key = "NamingTemplate",
                            Description = "Gabarit",
                            Type = "STRING",
                            Value = "IMP_{LIEU}_{MODELE}"
                        },
                        new
                        {
                            Key = "NamingEnabled",
                            Description = "Activer le nommage automatique",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "NamingSameShare",
                            Description = "Forcer le nom de partage",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "PasswordExpirationDays",
                            Description = "Expiration MDP (jours)",
                            Type = "INT",
                            Value = "90"
                        },
                        new
                        {
                            Key = "AdDomain",
                            Description = "Domaine Active Directory",
                            Type = "STRING",
                            Value = "mondomaine.lan"
                        },
                        new
                        {
                            Key = "AdUseServiceAccount",
                            Description = "Utiliser un compte spécifique ?",
                            Type = "BOOL",
                            Value = "false"
                        },
                        new
                        {
                            Key = "AdServiceUser",
                            Description = "Compte lecture AD",
                            Type = "STRING",
                            Value = ""
                        },
                        new
                        {
                            Key = "AdServicePassword",
                            Description = "Mot de passe AD",
                            Type = "PASSWORD",
                            Value = ""
                        },
                        new
                        {
                            Key = "AdAdminEmails",
                            Description = "Mails alerte panne AD (séparés par ;)",
                            Type = "STRING",
                            Value = ""
                        });
                });

            modelBuilder.Entity("Autoprint.Shared.SystemError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOccured")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemErrors");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.AdRoleMapping", b =>
                {
                    b.HasOne("Autoprint.Server.Models.Security.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.RolePermission", b =>
                {
                    b.HasOne("Autoprint.Server.Models.Security.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoprint.Server.Models.Security.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.UserRole", b =>
                {
                    b.HasOne("Autoprint.Server.Models.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoprint.Server.Models.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Autoprint.Shared.Imprimante", b =>
                {
                    b.HasOne("Autoprint.Shared.Emplacement", "Emplacement")
                        .WithMany()
                        .HasForeignKey("EmplacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoprint.Shared.Modele", "Modele")
                        .WithMany()
                        .HasForeignKey("ModeleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emplacement");

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("Autoprint.Shared.Modele", b =>
                {
                    b.HasOne("Autoprint.Shared.Marque", "Marque")
                        .WithMany()
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoprint.Shared.Pilote", "Pilote")
                        .WithMany()
                        .HasForeignKey("PiloteId");

                    b.Navigation("Marque");

                    b.Navigation("Pilote");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Autoprint.Server.Models.Security.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
